[package]
name = "quickmail"
version = "0.1.0"
edition = "2021"

[dependencies]
lettre = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.4", features = ["derive"] }
keyring = "2.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
